branch-defaults:
  default:
    environment: sample-dev
    group_suffix: null
  master:
    environment: ag-web-dev
    group_suffix: null
environment-defaults:
  sample-dev:
    branch: null
    repository: null
global:
  application_name: ag-web
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: user2
  repository: null
  sc: git
  workspace_type: Application
